<?php
// the following constant will help ensure all other PHP files will only work as part of this API.
if (!defined('CONST_INCLUDE_KEY')){
  define('CONST_INCLUDE_KEY', 'd4e2ad09-b1c3-4d70-9a9a-0e6149302486');
}
$o=array(
  "_hide"=>array(
      "ds"=>array(
        "fn_group"=>"geodata",
        "action"=>"view_data",
        "collection"=>"show_table_data",
        "table_slug"=>"WIKI_TB_POSTS",
        "filters_type"=>"AND",
        "filters_string"=>array(
          array("value"=>"(post_type='cityplanner' OR post_type='card')"),
        ),
        "order_by"=>array(
          array("field"=>"pid"),
        ),
        "cols"=>array(
          "item_token",
          "post_modified",
          "post_type"
        ),
        "qy_name"=>"A"
      )
  )
);

$className = 'API_Handler';
$cApiHandler = new $className();
$o["response_type"] = "array";
$returnArray_0 = $cApiHandler->execCommand('watchdog_webapp',$o);

$o=array(
  "_hide"=>array(
      "ds"=>array(
        "fn_group"=>"geodata",
        "action"=>"view_data",
        "collection"=>"show_table_data",
        "table_slug"=>"TB_MAP",
        "filters_type"=>"AND",
        "filters_string"=>array(
          array("value"=>"(g_sitemap=true)"),
        ),
        "order_by"=>array(
          array("field"=>"pid"),
        ),
        "cols"=>array(
          "g_slug",
          "post_modified"
        ),
        "qy_name"=>"A"
      )
  )
);

$className = 'API_Handler';
$cApiHandler = new $className();
$o["response_type"] = "array";
$returnArray_1 = $cApiHandler->execCommand('watchdog_webapp',$o);

header ("Content-Type:text/xml");

?>
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="//www.cityplanner.it/fix-for-the-planet/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd">
  <?php 
    foreach ($returnArray_0['features'] as $key => $value) {
      if($value['properties']['post_type'] == 'cityplanner'){
        ?>
        <url>
          <loc><?php echo get_site_url();?>/</loc>
          <lastmod><?php echo gmdate('Y-m-d\TH:i:s+00:00', strtotime($value['properties']['post_modified']));?></lastmod>
        </url>
        <?php
      }
      else{
        ?>
        <url>
          <loc><?php echo get_site_url();?>/<?php echo $value['properties']['post_type'];?>/<?php echo $value['properties']['item_token'];?>/</loc>
          <lastmod><?php echo gmdate('Y-m-d\TH:i:s+00:00', strtotime($value['properties']['post_modified']));?></lastmod>
        </url>
        <?php
      }

    }
    foreach ($returnArray_1['features'] as $key => $value) {
      ?>
      <url>
        <loc><?php echo get_site_url();?>/geodashboard/map/<?php echo $value['properties']['g_slug'];?>/</loc>
        <lastmod><?php echo gmdate('Y-m-d\TH:i:s+00:00', strtotime($value['properties']['post_modified']));?></lastmod>
      </url>
      <?php
    }    
  ?>
</urlset>
<!-- XML Sitemap generated by <?php echo APP_NICKNAME;?> -->