geovar.tb=new Array();
geovar.tb.example_table=new Array();
geovar.tb.example_table.cols_show=new Array();
geovar.tb.pg_cittametropolitane=new Array();
geovar.tb.pg_cittametropolitane.cols_show=new Array();

// -- language_webapp - END
  // -- colonne_webapp;
geovar.tb.pg_cittametropolitane.objectid=new Array();
geovar.tb.pg_cittametropolitane.objectid.hidden = '1';
geovar.tb.pg_cittametropolitane.objectid.mylayer = 'pg_cittametropolitane';
geovar.tb.pg_cittametropolitane.objectid.unita_misura = '';
geovar.tb.pg_cittametropolitane.objectid.formato = 'text';
geovar.tb.pg_cittametropolitane.objectid.variable = 'objectid';
geovar.tb.pg_cittametropolitane.objectid.etichetta_applicazione = 'Objectid';
geovar.tb.pg_cittametropolitane.objectid.descrizione = '';
geovar.tb.pg_cittametropolitane.objectid.cat = '';
geovar.tb.pg_cittametropolitane.objectid.report = '';
geovar.tb.pg_cittametropolitane.objectid.eliminato = '0';
geovar.tb.pg_cittametropolitane.objectid.required = '0';
geovar.tb.pg_cittametropolitane.objectid.input_typ = 'text';
geovar.tb.pg_cittametropolitane.cod_reg=new Array();
geovar.tb.pg_cittametropolitane.cod_reg.descrizione = 'Codice Regione';
geovar.tb.pg_cittametropolitane.cod_reg.mylayer = 'pg_cittametropolitane';
geovar.tb.pg_cittametropolitane.cod_reg.unita_misura = '';
geovar.tb.pg_cittametropolitane.cod_reg.formato = 'text';
geovar.tb.pg_cittametropolitane.cod_reg.variable = 'cod_reg';
geovar.tb.pg_cittametropolitane.cod_reg.etichetta_applicazione = 'Cod reg';
geovar.tb.pg_cittametropolitane.cod_reg.cat = '';
geovar.tb.pg_cittametropolitane.cod_reg.report = '';
geovar.tb.pg_cittametropolitane.cod_reg.eliminato = '0';
geovar.tb.pg_cittametropolitane.cod_reg.hidden = '0';
geovar.tb.pg_cittametropolitane.cod_reg.required = '0';
geovar.tb.pg_cittametropolitane.cod_reg.input_typ = 'text';
geovar.tb.pg_cittametropolitane.cols_show.push('cod_reg');
geovar.tb.pg_cittametropolitane.cod_pro=new Array();
geovar.tb.pg_cittametropolitane.cod_pro.mylayer = 'pg_cittametropolitane';
geovar.tb.pg_cittametropolitane.cod_pro.unita_misura = '';
geovar.tb.pg_cittametropolitane.cod_pro.formato = 'text';
geovar.tb.pg_cittametropolitane.cod_pro.variable = 'cod_pro';
geovar.tb.pg_cittametropolitane.cod_pro.etichetta_applicazione = 'Cod pro';
geovar.tb.pg_cittametropolitane.cod_pro.descrizione = '';
geovar.tb.pg_cittametropolitane.cod_pro.cat = '';
geovar.tb.pg_cittametropolitane.cod_pro.report = '';
geovar.tb.pg_cittametropolitane.cod_pro.eliminato = '0';
geovar.tb.pg_cittametropolitane.cod_pro.hidden = '0';
geovar.tb.pg_cittametropolitane.cod_pro.required = '0';
geovar.tb.pg_cittametropolitane.cod_pro.input_typ = 'text';
geovar.tb.pg_cittametropolitane.cols_show.push('cod_pro');


geovar.tb.pt_cities_corporations={
  'type': 'Feature',
  'properties': {
    'marker-color': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'Mytype',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':true,
      //'required':false,
      
    },
    'marker-size': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'Mytype',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':true,
      //'required':false,
    },
    'marker-symbol': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'Mytype',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':true,
      //'required':false,
    },
    'Corporation': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'Corporation',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':false,
      //'required':false,
    },
    'City': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'City',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':false,
      //'required':false,
    },
    'Nation': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'Nation',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':false,
      //'required':false,
    },
    'ref': {
      'formato':'link',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'Reference',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':false,
      //'required':false,
    },
    'Neighborhood': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'Neighborhood',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':false,
      //'required':false,
    }
  },
  'geometry': {
    'type': 'Point'
  }
}

geovar.tb.pt_centriassistenza={
  'type': 'Feature',
  'properties': {
    'centroassistenza': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      'etichetta_applicazione':'Agency: Name',
      'eliminato':false,
      'hidden':false,
    },
    'nome': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      'etichetta_applicazione':'Agency: Codice Agenzia',
      'eliminato':false,
      'hidden':false,
    },
    'tipo': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      'etichetta_applicazione':'Tipo',
      'eliminato':false,
      'hidden':false,
    },
    'indirizzo': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      'etichetta_applicazione':'Indirizzo',
      'eliminato':false,
      'hidden':false,
    },
    'cap': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      //'variable':'mytype',
      'etichetta_applicazione':'CAP',
      //'descrizione':'',
      //'cat':'',
      //'report':'',
      'eliminato':false,
      'hidden':false,
      //'required':false,
    },
    'comune': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      'etichetta_applicazione':'Comune',
      'eliminato':false,
      'hidden':false,
    },
    'provincia': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      'etichetta_applicazione':'Provincia',
      'eliminato':false,
      'hidden':false,
    },
    'priorita': {
      'formato':'text',
      'input_typ':'text',
      'unita_misura':'',
      'etichetta_applicazione':'Priorità',
      'eliminato':false,
      'hidden':false,
    },
  },
  'geometry': {
    'type': 'Point'
  }
}

geovar.tb.PT_SHOPS={
  'type': 'Feature',
  'properties': {
    'pid': {
      'etichetta_applicazione': 'ID Negozio',
      'unita_misura': null,
      'formato': null,
      'descrizione': null,
      'cat': null,
      'myorder': 1,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'id_old': {
      'etichetta_applicazione': 'ID Negozio (vecchio)',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': 'Valido fino a settembre 2020',
      'cat': null,
      'myorder': 2,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'id_negozio': {
      'etichetta_applicazione': 'ID Negozio',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': 'Nuovo campo non presente in COOP Liguria',
      'cat': null,
      'myorder': 2,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'codice_sito': {
      'etichetta_applicazione': 'Codice Sito',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': 'Inserire numero progressivo che parte per i nuovi da 20.000',
      'cat': null,
      'myorder': 3,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'gruppo': {
      'etichetta_applicazione': 'Gruppo',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Generato dal campo [Insegna esposta]',
      'cat': null,
      'myorder': 4,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'insegna_esposta': {
      'etichetta_applicazione': 'Insegna Esposta',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Dato vincolato al Gruppo',
      'cat': null,
      'myorder': 5,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 1
    },
    'insegna_precedente': {
      'etichetta_applicazione': 'Insegna Precedente',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 6,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 0
    },
    'insegna_gruppo': {
      'etichetta_applicazione': 'Insegna di Gruppo',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 7,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 0
    },
    'codice_ancc': {
      'etichetta_applicazione': 'Codice ANCC',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': 'Se compilato con 0 è un negozio della concorrenza, se contiene un numero diverso da 0 è un negozio di COOP Liguria',
      'cat': null,
      'myorder': 8,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'number',
      'required': 1
    },
    'post_author_txt': {
      'etichetta_applicazione': 'Utente rilevatore',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Utente che sta effettuando la rilevazione connesso all\'applicazione',
      'cat': null,
      'myorder': 9,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'post_date': {
      'etichetta_applicazione': 'Data Rilevazione',
      'unita_misura': null,
      'formato': 'date_picker',
      'descrizione': null,
      'cat': null,
      'myorder': 10,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'data_apertura': {
      'etichetta_applicazione': 'Data Apertura Negozio',
      'unita_misura': null,
      'formato': 'date_picker',
      'descrizione': null,
      'cat': null,
      'myorder': 11,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'date',
      'required': 1
    },
    'post_editor_txt': {
      'etichetta_applicazione': 'Utente modifica',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Utente che modifica il negozio rilevato',
      'cat': null,
      'myorder': 12,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'post_modified': {
      'etichetta_applicazione': 'Data Modifica',
      'unita_misura': null,
      'formato': 'date_picker',
      'descrizione': null,
      'cat': null,
      'myorder': 13,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'data_chiusura': {
      'etichetta_applicazione': 'Data Chiusura',
      'unita_misura': null,
      'formato': 'date_picker',
      'descrizione': 'Data Chiusura se compilata il negozio è stato chiuso',
      'cat': null,
      'myorder': 14,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'date',
      'required': 0
    },
    'data_ristrutturazione': {
      'etichetta_applicazione': 'Data Ristrutturazione',
      'unita_misura': null,
      'formato': 'date_picker',
      'descrizione': null,
      'cat': null,
      'myorder': 15,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'date',
      'required': 0
    },
    'data_validazione': {
      'etichetta_applicazione': 'data_validazione',
      'unita_misura': null,
      'formato': 'date_picker',
      'descrizione': 'Data nella quale è stato validato il punto dal supervisore, campo visibile solo al supervisore',
      'cat': null,
      'myorder': 16,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'ragione_sociale': {
      'etichetta_applicazione': 'Ragione Sociale',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 17,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 1
    },
    'tipo_conduzione_negozio': {
      'etichetta_applicazione': 'Tipo Conduzione Negozio',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 18,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 0
    },
    'note_negozio': {
      'etichetta_applicazione': 'Note di Negozio',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 19,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'textarea',
      'required': 0
    },
    'provincia': {
      'etichetta_applicazione': 'Provincia',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Campo assegnato automaticamente dalle sezioni di censimento',
      'cat': null,
      'myorder': 20,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'area_gravitazionale': {
      'etichetta_applicazione': 'Area Gravitazionale',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 21,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'codice_area_gravitazionale': {
      'etichetta_applicazione': 'Codice Area Gravitazionale',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': 22,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'municipality': {
      'etichetta_applicazione': 'Comune',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Campo assegnato automaticamente dalle sezioni di censimento',
      'cat': null,
      'myorder': 23,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'codice_comune': {
      'etichetta_applicazione': 'Codice Comune',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': 'Campo assegnato automaticamente dalle sezioni di censimento',
      'cat': null,
      'myorder': 24,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'municipio': {
      'etichetta_applicazione': 'Municipio',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 25,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'text',
      'required': 0
    },
    'unita_urbanistica': {
      'etichetta_applicazione': 'Unita Urbanistica',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Campo assegnato automaticamente dalle sezioni di censimento',
      'cat': null,
      'myorder': 26,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'codice_unita_urbanistica': {
      'etichetta_applicazione': 'Codice Unita Urbanistica',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Campo assegnato automaticamente dalle sezioni di censimento',
      'cat': null,
      'myorder': 27,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'pinlat': {
      'etichetta_applicazione': 'Latitudine',
      'unita_misura': null,
      'formato': 'm10',
      'descrizione': null,
      'cat': null,
      'myorder': 28,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'pinlng': {
      'etichetta_applicazione': 'Longitudine',
      'unita_misura': null,
      'formato': 'm10',
      'descrizione': null,
      'cat': null,
      'myorder': 29,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'contesto_urbano': {
      'etichetta_applicazione': 'Contesto Urbano',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 30,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 0
    },
    'accessibilita_negozio': {
      'etichetta_applicazione': 'Accessibilità Negozio',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': '(F)',
      'cat': null,
      'myorder': 31,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 0
    },
    'street': {
      'etichetta_applicazione': 'Indirizzo Immobile',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 32,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'text',
      'required': 1
    },
    'indirizzo_scontrino': {
      'etichetta_applicazione': 'Indirizzo Scontrino',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 33,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'text',
      'required': 1
    },
    'indirizzo_normalizzato': {
      'etichetta_applicazione': 'Indirizzo Normalizzato',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 34,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'text',
      'required': 0
    },
    'superficie_food': {
      'etichetta_applicazione': 'Superficie Food',
      'unita_misura': 'Metri Quadri',
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': 35,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'number',
      'required': 0
    },
    'superficie_non_food': {
      'etichetta_applicazione': 'Superficie Non Food',
      'unita_misura': 'Metri Quadri',
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': 36,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'number',
      'required': 0
    },
    'superficie_totale': {
      'etichetta_applicazione': 'Superficie Totale',
      'unita_misura': 'Metri Quadri',
      'formato': 'm',
      'descrizione': 'Somma tot sup food + non food',
      'cat': null,
      'myorder': 37,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'n_casse': {
      'etichetta_applicazione': 'N° Casse',
      'unita_misura': 'Valore',
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': 38,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'number',
      'required': 0
    },
    'n_parcheggi_privati': {
      'etichetta_applicazione': 'N° Parcheggi privati',
      'unita_misura': 'Valore',
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': 39,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'number',
      'required': 0
    },
    'parcheggio_pubblico': {
      'etichetta_applicazione': 'Parcheggio Pubblico',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 40,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'text',
      'required': 0
    },
    'orario': {
      'etichetta_applicazione': 'Orario',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 41,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 0
    },
    'apertura_domenicale': {
      'etichetta_applicazione': 'Apertura Domenicale',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 42,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'text',
      'required': 0
    },
    'vendite_food_stimate': {
      'etichetta_applicazione': 'Vendite Food Stimate',
      'unita_misura': 'Euro',
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': 43,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'number',
      'required': 0
    },
    'vendite_non_food_stimate': {
      'etichetta_applicazione': 'Vendite Non Food Stimate',
      'unita_misura': 'Euro',
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': 44,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'number',
      'required': 0
    },
    'vendite_totali_stimate': {
      'etichetta_applicazione': 'Vendite Totali Stimate',
      'unita_misura': 'Euro',
      'formato': 'm',
      'descrizione': 'Aggiornato automaticamente dalla somma di Vendite Food Stimate + Vendite Non Food Stimate',
      'cat': null,
      'myorder': 45,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'anno_stima_vendite': {
      'etichetta_applicazione': 'Anno Stima Vendite',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'inserire solo anno',
      'cat': null,
      'myorder': 46,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'text',
      'required': 0
    },
    'ruolo_negozio': {
      'etichetta_applicazione': 'Ruolo Negozio',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 47,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 1
    },
    'tipo_negozio': {
      'etichetta_applicazione': 'Tipo Negozio',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 48,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'select',
      'required': 1
    },
    'rilevazione': {
      'etichetta_applicazione': 'rilevazione',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Rilevazione [on site], [remoto] se la distanza rilevazione è maggiorne di 250 inserire remoto',
      'cat': null,
      'myorder': 49,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'device_rilevazione': {
      'etichetta_applicazione': 'Device Rilevazione',
      'unita_misura': null,
      'formato': 'date_picker',
      'descrizione': '[desktop], [mobile]',
      'cat': 'system',
      'myorder': 50,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'distanza': {
      'etichetta_applicazione': 'Distanza della rilevazione',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': 'system',
      'myorder': 51,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'usrlng': {
      'etichetta_applicazione': 'Longitudine del rilevatore',
      'unita_misura': null,
      'formato': 'm10',
      'descrizione': null,
      'cat': 'system',
      'myorder': 52,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'usrlat': {
      'etichetta_applicazione': 'Latitudine del  rilevatore',
      'unita_misura': null,
      'formato': 'm10',
      'descrizione': null,
      'cat': 'system',
      'myorder': 53,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'codsez': {
      'etichetta_applicazione': 'Codice sezione di censimento',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Campo assegnato automaticamente dalle sezioni di censimento',
      'cat': null,
      'myorder': 54,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'photo_scontrino_filename': {
      'etichetta_applicazione': 'Foto scontrino',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 55,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'photo_insegna_filename': {
      'etichetta_applicazione': 'Foto insegna',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 56,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'photo_zona_filename': {
      'etichetta_applicazione': 'Foto zona',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 57,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'geocode': {
      'etichetta_applicazione': 'Precisione geocodifica',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': null,
      'myorder': 58,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'fonte_geocodifica': {
      'etichetta_applicazione': 'Fonte geocodifica',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'Default inserire sempre COOP Liguria',
      'cat': null,
      'myorder': 59,
      'mylayer': 'PT_SHOPS',
      'hidden': 0,
      'input_typ': 'auto+edit',
      'required': 0
    },
    'photo_scontrino': {
      'etichetta_applicazione': 'Foto scontrino ID',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': 'automatico numero progressivo così es 1_fotoscontrino',
      'cat': 'system',
      'myorder': 60,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'photo_insegna': {
      'etichetta_applicazione': 'Foto insegna ID',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': 'automatico numero progressivo così es 1_fotoinsegna',
      'cat': 'system',
      'myorder': 61,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'photo_zona': {
      'etichetta_applicazione': 'Foto zona ID',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': 'automatico numero progressivo così es 1_fotozona',
      'cat': 'system',
      'myorder': 62,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'photo_scontrino_url': {
      'etichetta_applicazione': 'Foto scontrino_url',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': 'system',
      'myorder': 63,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'photo_insegna_url': {
      'etichetta_applicazione': 'Foto insegna_url',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': 'system',
      'myorder': 64,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'photo_zona_url': {
      'etichetta_applicazione': 'Foto zona_url',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': 'system',
      'myorder': 65,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'text',
      'required': 0
    },
    'accuracy': {
      'etichetta_applicazione': 'GPS precisione',
      'unita_misura': 'Metri',
      'formato': 'm',
      'descrizione': null,
      'cat': 'system',
      'myorder': 66,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'codgeo': {
      'etichetta_applicazione': 'codgeo',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': 'system',
      'myorder': 67,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'closed': {
      'etichetta_applicazione': 'closed',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': 'system',
      'myorder': 68,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'post_status': {
      'etichetta_applicazione': 'post_status',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': null,
      'cat': 'system',
      'myorder': 69,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'totale_prodotti': {
      'etichetta_applicazione': 'Totale prodotti',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': 'system',
      'myorder': 70,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'informatica_1434': {
      'etichetta_applicazione': 'INFORMATICA 1434',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'surgelati_1058': {
      'etichetta_applicazione': 'SURGELATI 1058',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'salumi_latticini_serviti_1047': {
      'etichetta_applicazione': 'SALUMI LATTICINI SERVITI 1047',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'salumi_latticini_self_1048': {
      'etichetta_applicazione': 'SALUMI LATTICINI SELF 1048',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'rosticceria_1049': {
      'etichetta_applicazione': 'ROSTICCERIA 1049',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'ristoro_3322': {
      'etichetta_applicazione': 'RISTORO 3322',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'igiene_casa_e_persona_e_profumeria_3': {
      'etichetta_applicazione': 'IGIENE CASA E PERSONA E PROFUMERIA 3',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'grandi_magazzini_40': {
      'etichetta_applicazione': 'GRANDI MAGAZZINI 40',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'prodotti_per_prima_infanzia_2': {
      'etichetta_applicazione': 'PRODOTTI PER PRIMA INFANZIA 2',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'piante_e_fiori_1573': {
      'etichetta_applicazione': 'PIANTE & FIORI 1573',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'pesce_servito_1053': {
      'etichetta_applicazione': 'PESCE SERVITO 1053',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'pesce_self_1196': {
      'etichetta_applicazione': 'PESCE SELF 1196',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'grandi_e_piccoli_elettrodomestici_e_multimedia_20': {
      'etichetta_applicazione': 'GRANDI E PICCOLI ELETTRODOMESTICI E MULTIMEDIA 20',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'pasticceria_fresca_1057': {
      'etichetta_applicazione': 'PASTICCERIA FRESCA 1057',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'pane_servito_1054': {
      'etichetta_applicazione': 'PANE SERVITO 1054',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'girarrosto_1051': {
      'etichetta_applicazione': 'GIRARROSTO 1051',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'pane_self_1197': {
      'etichetta_applicazione': 'PANE SELF 1197',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'giocattoli_16': {
      'etichetta_applicazione': 'GIOCATTOLI 16',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'forno_1056': {
      'etichetta_applicazione': 'FORNO 1056',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'fast_food_1544': {
      'etichetta_applicazione': 'FAST FOOD 1544',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'extraintegrato_1198': {
      'etichetta_applicazione': 'EXTRAINTEGRATO 1198',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'tessili_per_la_casa_7': {
      'etichetta_applicazione': 'TESSILI PER LA CASA 7',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'drugstore_3124': {
      'etichetta_applicazione': 'DRUGSTORE 3124',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'cura_e_cibo_per_animali_1': {
      'etichetta_applicazione': 'CURA E CIBO PER ANIMALI 1',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'ortofrutta_sfusa_1050': {
      'etichetta_applicazione': 'ORTOFRUTTA SFUSA 1050',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'ortofrutta_self_1195': {
      'etichetta_applicazione': 'ORTOFRUTTA SELF 1195',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'casalinghi_e_consumabili_per_la_casa_5': {
      'etichetta_applicazione': 'CASALINGHI E CONSUMABILI PER LA CASA 5',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'cancelleria_18': {
      'etichetta_applicazione': 'CANCELLERIA 18',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'calzature_uomo_donna_bambini_9': {
      'etichetta_applicazione': 'CALZATURE (UOMO, DONNA, BAMBINI) 9',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'multimedia_1433': {
      'etichetta_applicazione': 'MULTIMEDIA 1433',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'bric\u0442_e_tempo_libero_e_giardinaggio_15': {
      'etichetta_applicazione': 'BRICO E TEMPO LIBERO E GIARDINAGGIO 15',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'mobili_e_arredi_8': {
      'etichetta_applicazione': 'MOBILI E ARREDI 8',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'bazar_30': {
      'etichetta_applicazione': 'BAZAR 30',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'articoli_e_abbigliamento_sportivi_14': {
      'etichetta_applicazione': 'ARTICOLI E ABBIGLIAMENTO SPORTIVI 14',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'appenderia_1063': {
      'etichetta_applicazione': 'APPENDERIA 1063',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'macelleria_servita_1044': {
      'etichetta_applicazione': 'MACELLERIA SERVITA 1044',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'macelleria_self_1046': {
      'etichetta_applicazione': 'MACELLERIA SELF 1046',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'libri_e_giornali_19': {
      'etichetta_applicazione': 'LIBRI E GIORNALI 19',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'abbigliamento_11': {
      'etichetta_applicazione': 'ABBIGLIAMENTO 11',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'iper_non_food_3150': {
      'etichetta_applicazione': 'IPER NON FOOD 3150',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'intimo_e_calze_uomo_donna_bambini_10': {
      'etichetta_applicazione': 'INTIMO E CALZE (UOMO, DONNA, BAMBINI) 10',
      'unita_misura': null,
      'formato': 'm',
      'descrizione': null,
      'cat': null,
      'myorder': null,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    },
    'regione': {
      'etichetta_applicazione': 'regione',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'regione',
      'cat': 'z',
      'myorder': 0,
      'mylayer': 'regioni',
      'hidden': 0,
      'input_typ': 'auto',
      'required': 0
    },
    'origine': {
      'etichetta_applicazione': 'origine',
      'unita_misura': null,
      'formato': 'text',
      'descrizione': 'tabella di origine',
      'cat': null,
      'myorder': 0,
      'mylayer': 'PT_SHOPS',
      'hidden': 1,
      'input_typ': 'auto',
      'required': 0
    }
  },
  'geometry': {
    'type': 'Point'
  }
}
