geovar.language_webapp.it_IT.lat_start=41.891594;
geovar.language_webapp.en_GB.lat_start=41.891594;
geovar.language_webapp.it_IT.lng_start=12.490448;
geovar.language_webapp.en_GB.lng_start=12.490448;
geovar.language_webapp.it_IT.label_attribution1='Leaflet - © OpenStreetMap © CartoDB';
geovar.language_webapp.en_GB.label_attribution1='Leaflet - © OpenStreetMap © CartoDB';
geovar.language_webapp.it_IT.label_attribution2='Leaflet - © OpenStreetMap © Stamen Design';
geovar.language_webapp.en_GB.label_attribution2='Leaflet - © OpenStreetMap © Stamen Design';
geovar.language_webapp.it_IT.tile_map01_attr='tile_osmmapnik_attr[3]';
geovar.language_webapp.en_GB.tile_map01_attr='tile_osmmapnik_attr[3]';
geovar.language_webapp.it_IT.tile_map01_url='https://{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}.png';
geovar.language_webapp.en_GB.tile_map01_url='https://{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}.png';
geovar.language_webapp.it_IT.tile_map01_url_label='https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png';
geovar.language_webapp.en_GB.tile_map01_url_label='https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png';
geovar.language_webapp.it_IT.tile_map02_url='https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png';
geovar.language_webapp.en_GB.tile_map02_url='https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png';
geovar.language_webapp.it_IT.tile_map03_url='https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png';
geovar.language_webapp.en_GB.tile_map03_url='https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png';
geovar.language_webapp.it_IT.tile_map03_url='https://{s}.basemaps.cartocdn.com/rastertiles/light_nolabels/{z}/{x}/{y}.png';
geovar.language_webapp.en_GB.tile_map03_url='https://{s}.basemaps.cartocdn.com/rastertiles/light_nolabels/{z}/{x}/{y}.png';
geovar.language_webapp.it_IT.tile_map01_attr='&copy; <a href="httpa://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>';
geovar.language_webapp.en_GB.tile_map01_attr='&copy; <a href="httpa://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>';
geovar.language_webapp.it_IT.zoom_result=15;
geovar.language_webapp.en_GB.zoom_result=15;
geovar.language_webapp.it_IT.zoom_result_route=19;
geovar.language_webapp.en_GB.zoom_result_route=19;
geovar.language_webapp.it_IT.zoom_start=6.35;
geovar.language_webapp.en_GB.zoom_start=6.35;